### ISSUE TITLE
No method error for `config.staccato`

### ISSUE THREAD

**Issue by mmhan** [tpitale/staccato-rails#10]
I'm putting the configurations in my `config/environments/test.rb` file as this
```
config.staccato.pageviews = false
```

And I get: 

```
undefined method `staccato' for #<Rails::Application::Configuration:0x007feb4ec2f8d0> (NoMethodError)
```

**Comment by tpitale** [comment]
Whic version of rails are you using?

**Comment by mmhan** [comment]
Hi, it's 4.2.5

**Comment by tpitale** [comment]
Does the configuration work in other environments …?

**Comment by mmhan** [comment]
No, I have confirmed that it doesn't work in other environments either.

**Comment by tpitale** [comment]
What are you doing in your Gemfile?

My best guess right now is that `Rails` isn't defined before https://github.com/tpitale/staccato-rails/blob/master/lib/staccato-rails.rb is required. Which would prevent https://github.com/tpitale/staccato-rails/blob/master/lib/staccato/railtie.rb#L3-L11 from running.

**Comment by mmhan** [comment]
That's very interesting. I tried moving up the line that declares `gem
'staccato'` up to earlier lines in the file and it worked.

I'll do some more tests and try to give you more information about the gem
that stccato is in conflict with.

**Comment by tpitale** [comment]
@mmhan Thanks!

**Comment by tpitale** [comment]
Or, if you feel like it, sharing your gemfile and I can go through a search of the gems that might be conflicting.

**Comment by mmhan** [comment]
>  I tried moving up the line that declares `gem 'staccato'` up to earlier lines in the file and it worked.

My bad, that didn't work. No matter where that declaration is, it's still producing error.

**Comment by mmhan** [comment]
I have tried the gem in a fresh project and confirmed that it works. It's gonna be quite a pain to isolate the conflicting gem though, and I'm unable to share my Gemfile with you.

**Comment by mmhan** [comment]
I've reproduced the bug in a fresh project. Here's the repo https://github.com/mmhan/staccato_issue10

**Comment by tpitale** [comment]
There's no mention of staccato-rails in the Gemfile.

**Comment by tpitale** [comment]
https://github.com/tpitale/staccato-rails/blob/master/README.md#installation

**Comment by mmhan** [comment]
Erm.. Here it is https://github.com/mmhan/staccato_issue10/blob/master/Gemfile#L17

**Comment by mmhan** [comment]
Argh! My bad, I was using `gem 'staccato'` instead of `gem 'staccato-rails'`

**Comment by tpitale** [comment]
@mmhan I just pushed a release to rubygems, so you can drop the `github` and `branch` sections in the gemfile. A simple `gem "staccato-rails"` should do, now.
