### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by jmscholen** [tpitale/staccato-rails#11]
This is the first that I have installed this gem. This is not happening on my local when I am loading the page that I am trying to have events tracked, but when I push to our staging environment and I load the page where the tracker has been placed, it redirects at the code:
`tracker.event(category: 'staging', action: 'index', label: 'test', value: 1)`

thanks.

**Comment by tpitale** [comment]
Can you provide some more information? A backtrace, any details in the error itself, relevant configuration.

My only guess without any other context is misconfiguration in staging. Not much to go on, though.

**Comment by jmscholen** [comment]
Sorry about the lack detail. Logs give no information or back trace. All I
know that is happening is that it's redirecting to "/" when it hits the
tracker instance. Ill try some other things to see info can get you more
information.

-- 
Jeff Scholen

**Comment by tpitale** [comment]
What is "it" that is "redirecting to /"?

The `tracker` makes an http request to google. If google is returning a 301, we generally don't care. But I've never seen a 301 response.

Regardless, if you are getting a 301, something in the request is likely broken from misconfiguration or malformed by input.

I'll get back to you on ways to check the request and response from google, but it'll include some form of extra info from them about why it would redirect.

**Comment by tpitale** [comment]
@jmscholen this is actually going to be within Staccato, not this library. If you could open an issue there. Thanks!

**Comment by jmscholen** [comment]
ok..will do..https://github.com/tpitale/staccato/issues/68
